/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
use std::net::Ipv4Addr;

use ::rpc::forge as rpc;
use gtmpl_derive::Gtmpl;
use utils::models::dhcp::HostConfig;

use crate::HBNDeviceNames;

/// The path we write in non-NVUE mode, when using dhcp-relay (versus dhcp-server)
pub const RELAY_PATH: &str = "etc/supervisor/conf.d/default-isc-dhcp-relay.conf";

/// The path NVUE writes if we're using dhcp-relay
pub const RELAY_PATH_NVUE: &str = "etc/supervisor/conf.d/isc-dhcp-relay-default";

pub const SERVER_PATH: &str = "etc/supervisor/conf.d/default-forge-dhcp-server.conf";
pub const SERVER_CONFIG_PATH: &str = "var/support/forge-dhcp/conf/dhcp.yaml";
pub const SERVER_HOST_CONFIG_PATH: &str = "var/support/forge-dhcp/conf/host.yaml";

pub const TMPL_EMPTY: &str = "# Auto-generated by Forge!";
const TMPL_SERVER: &str = include_str!("../templates/default-forge-dhcp-server.conf");

pub const RELOAD_CMD: &str = "supervisorctl update";
// Since we don't update default-forge-dhcp-server.conf file, supervisord does not restart it on
// `supervisorctl update` command.
pub const RELOAD_DHCP_SERVER: &str =
    "supervisorctl update;supervisorctl restart forge-dhcp-server-default";

pub const STOP_DHCP_SERVER: &str =
    "supervisorctl update;supervisorctl stop forge-dhcp-server-default";

/// Generate default-forge-dhcp-server.conf
pub fn build_server_supervisord_config(
    conf: DhcpServerSupervisordConfig,
) -> Result<String, eyre::Report> {
    let params = TmplDHCServerConfigParameters {
        Interfaces: conf.interfaces,
        Autostart: conf.autostart,
    };
    gtmpl::template(TMPL_SERVER, params).map_err(|e| e.into())
}

/// An empty default-isc-dhcp-relay.conf
pub fn blank() -> String {
    gtmpl::template(TMPL_EMPTY, "").expect("dhcp blank template cannot fail")
}

pub fn build_server_config(
    pxe_ip: Ipv4Addr,
    ntpservers: Vec<Ipv4Addr>,
    nameservers: Vec<Ipv4Addr>,
    loopback_ip: Ipv4Addr,
) -> Result<String, eyre::Report> {
    let dhcp_config = utils::models::dhcp::DhcpConfig::from_forge_dhcp_config(
        pxe_ip,
        ntpservers,
        nameservers,
        loopback_ip,
    )?;

    Ok(serde_yaml::to_string(&dhcp_config)?)
}

pub fn build_server_host_config(
    conf: rpc::ManagedHostNetworkConfigResponse,
    hbn_devic_names: &HBNDeviceNames,
) -> Result<String, eyre::Report> {
    Ok(serde_yaml::to_string(&HostConfig::try_from(
        conf,
        hbn_devic_names.reps[0],
        hbn_devic_names.virt_rep_begin,
        hbn_devic_names.sf_id,
    )?)?)
}

pub struct DhcpServerSupervisordConfig {
    pub interfaces: Vec<String>,
    pub autostart: bool,
}

//
// Go template object, hence allow(non_snake_case)
//

#[allow(non_snake_case)]
#[derive(Clone, Gtmpl)]
struct TmplDHCRelayConfigParameters {
    Uplinks: Vec<String>,
    VlanIDs: Vec<u32>,
    Servers: Vec<String>,
    RemoteId: String,
}

#[allow(non_snake_case)]
#[derive(Clone, Gtmpl)]
struct TmplDHCServerConfigParameters {
    Interfaces: Vec<String>,
    Autostart: bool,
}
