/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
use std::path::PathBuf;

use tonic_client_wrapper::codegen;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").unwrap());
    let autogenerated_rust_output_directory = PathBuf::from("src/protos");
    // The reflection path is part of the output directory (which might be debug or release),
    // so that different builds get a different binary file and concurrent builds don't collide
    let reflection = out_dir.join("forge.bin");

    tonic_prost_build::configure()
        .file_descriptor_set_path(reflection)
        .type_attribute(
            ".google.protobuf.Timestamp",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            ".forge.DeletedFilter",
            "#[cfg_attr(feature = \"cli\", derive(clap::ValueEnum))]",
        )
        .extern_path(".google.protobuf.Duration", "crate::Duration")
        .extern_path(".google.protobuf.Timestamp", "crate::Timestamp")
        .extern_path(".common.DomainId", "::carbide_uuid::domain::DomainId")
        .extern_path(".common.DpaInterfaceId", "::carbide_uuid::dpa_interface::DpaInterfaceId")
        .extern_path(".common.IBPartitionId", "::carbide_uuid::infiniband::IBPartitionId")
        .extern_path(".common.InstanceId", "::carbide_uuid::instance::InstanceId")
        .extern_path(".common.MachineId", "::carbide_uuid::machine::MachineId")
        .extern_path(".common.MachineInterfaceId", "::carbide_uuid::machine::MachineInterfaceId")
        .extern_path(".common.NetworkPrefixId", "::carbide_uuid::network::NetworkPrefixId")
        .extern_path(".common.NetworkSegmentId", "::carbide_uuid::network::NetworkSegmentId")
        .extern_path(".common.PowerShelfId", "::carbide_uuid::power_shelf::PowerShelfId")
        .extern_path(".common.RackId", "::carbide_uuid::rack::RackId")
        .extern_path(".common.NVLinkPartitionId", "::carbide_uuid::nvlink::NvLinkPartitionId")
        .extern_path(".common.NVLinkLogicalPartitionId", "::carbide_uuid::nvlink::NvLinkLogicalPartitionId")
        .extern_path(".common.NVLinkDomainId", "::carbide_uuid::nvlink::NvLinkDomainId")
        .extern_path(".common.RemediationId", "carbide_uuid::dpu_remediations::RemediationId")
        .extern_path(".common.SwitchId", "::carbide_uuid::switch::SwitchId")
        .extern_path(".common.VpcId", "::carbide_uuid::vpc::VpcId")
        .extern_path(".common.VpcPeeringId", "::carbide_uuid::vpc_peering::VpcPeeringId")
        .extern_path(".common.VpcPrefixId", "::carbide_uuid::vpc::VpcPrefixId")
        .extern_path(".common.ComputeAllocationId", "::carbide_uuid::compute_allocation::ComputeAllocationId")
        .extern_path(".measured_boot.MeasurementSystemProfileId", "::carbide_uuid::measured_boot::MeasurementSystemProfileId")
        .extern_path(".measured_boot.MeasurementSystemProfileAttrId", "::carbide_uuid::measured_boot::MeasurementSystemProfileAttrId")
        .extern_path(".measured_boot.MeasurementBundleId", "::carbide_uuid::measured_boot::MeasurementBundleId")
        .extern_path(".measured_boot.MeasurementBundleValueId", "::carbide_uuid::measured_boot::MeasurementBundleValueId")
        .extern_path(".measured_boot.MeasurementReportId", "::carbide_uuid::measured_boot::MeasurementReportId")
        .extern_path(".measured_boot.MeasurementReportValueId", "::carbide_uuid::measured_boot::MeasurementReportValueId")
        .extern_path(".measured_boot.MeasurementJournalId", "::carbide_uuid::measured_boot::MeasurementJournalId")
        .extern_path(".measured_boot.MeasurementApprovedMachineId", "::carbide_uuid::measured_boot::MeasurementApprovedMachineId")
        .extern_path(".measured_boot.MeasurementApprovedProfileId", "::carbide_uuid::measured_boot::MeasurementApprovedProfileId")
        .include_file("prost_common.rs")
        .type_attribute(".health", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute(
            ".machine_discovery",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            ".site_explorer",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            ".mlx_device",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.AdminForceDeleteMachineRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.AdminForceDeleteMachineResponse",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.ClientSecretBasic", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(".dns", "#[derive(serde::Serialize)]")
        .type_attribute("forge.FlatInterfaceConfig", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.InstanceInterfaceConfig",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.InstanceInterfaceConfig.network_details",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.InstanceIBInterfaceConfig",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("forge.InstanceUpdateStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.InstanceNetworkConfig", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.InstanceInfinibandConfig",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("forge.InstanceStorageConfig", "#[derive(serde::Serialize)]")
        .type_attribute("forge.TenantConfig", "#[derive(serde::Serialize)]")
        .type_attribute("forge.InstanceConfig", "#[derive(serde::Serialize)]")
        .type_attribute("forge.InstanceDpuExtensionServicesConfig", "#[derive(serde::Serialize)]")
        .type_attribute("forge.InstanceDpuExtensionServiceConfig", "#[derive(serde::Serialize)]")
        .type_attribute("forge.ManagedHostDpuExtensionServiceConfig", "#[derive(serde::Serialize)]")
        .type_attribute("forge.DpuExtensionService", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("forge.DpuExtensionServiceVersionInfo", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("forge.DpuExtensionServiceType", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("forge.DpuExtensionServiceIdList", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("forge.DpuExtensionServiceCredential", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("forge.DpuExtensionServiceCredential.type", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("forge.UsernamePassword", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("forge.DpuExtensionServiceStatusObservation", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("forge.DpuExtensionServiceComponent", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("forge.DpuExtensionServiceStatus", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("forge.DpuExtensionServiceObservability", "#[derive(serde::Serialize, serde::Deserialize)]")        
        .type_attribute("forge.DpuExtensionServiceObservabilityConfigPrometheus", "#[derive(serde::Serialize, serde::Deserialize)]") 
        .type_attribute("forge.DpuExtensionServiceObservabilityConfigLogging", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("forge.DpuExtensionServiceObservabilityConfig.config", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("forge.DpuExtensionServiceObservabilityConfig", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("forge.DpuExtensionServiceObservability.configs", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("forge.InstanceNVLinkConfig", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("forge.InstanceNVLinkGpuConfig", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("forge.InstanceNVLinkStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.InstanceNVLinkGpuStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NVLinkPartition", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NVLinkPartitionList", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NVLinkPartitionConfig", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NVLinkPartitionStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NVLinkPartitionGpuStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NVLinkLogicalPartition", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NVLinkLogicalPartitionList", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NVLinkLogicalPartitionConfig", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NVLinkLogicalPartitionStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NVLinkLogicalPartitionGpuStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.MachineNVLinkGpuStatusObservation", "#[derive(serde::Serialize)]")
        .type_attribute("forge.MachineNVLinkStatusObservation", "#[derive(serde::Serialize)]")
        .type_attribute("common.NVLinkDomainId", "#[derive(serde::Serialize)]")
        .type_attribute("common.NVLinkLogicalPartitionId", "#[derive(serde::Serialize)]")
        .type_attribute("common.NVLinkPartitionId", "#[derive(serde::Serialize)]")
        .type_attribute("forge.MachineNVLinkInfo", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NVLinkGpu", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.InstanceInterfaceStatus",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.InstanceIBInterfaceStatus",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.InstanceNetworkStatus", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.InstanceInfinibandStatus",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.InstanceStorageStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.InstanceDpuExtensionServicesStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.InstanceDpuExtensionServiceStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.InstanceTenantStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.InstanceStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.Instance", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.Metadata",
            "#[derive(serde::Serialize, serde::Deserialize, Eq)]",
        )
        .type_attribute(
            "forge.Label",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "forge.InstancePhoneHomeLastContactRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.InstancePhoneHomeLastContactResponse",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.InstanceList", "#[derive(serde::Serialize)]")
        .type_attribute("forge.Machine", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.MachineCapabilitiesSet",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.MachineCapabilityAttributesCpu",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.MachineCapabilityAttributesGpu",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.MachineCapabilityAttributesMemory",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.MachineCapabilityAttributesStorage",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.MachineCapabilityAttributesNetwork",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.MachineCapabilityAttributesInfiniband",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.MachineCapabilityAttributesDpu",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.MachineList", "#[derive(serde::Serialize)]")
        .type_attribute("forge.MachineEvent", "#[derive(serde::Serialize)]")
        .type_attribute("forge.MachineInterface", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.InfinibandStatusObservation",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.MachineIbInterface", "#[derive(serde::Serialize)]")
        .type_attribute("forge.MachineState", "#[derive(serde::Serialize)]")
        .type_attribute("forge.MachineArchitecture", "#[derive(serde::Serialize)]")
        .type_attribute("forge.MachineInventory", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.MachineInventorySoftwareComponent",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.HealthReportOverride", "#[derive(serde::Serialize)]")
        .type_attribute("forge.HealthOverrideOrigin", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute(
            "forge.ManagedHostNetworkConfig",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.ManagedHostNetworkConfigResponse",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.RoutingProfile",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.TrafficInterceptConfig", "#[derive(serde::Serialize)]")
        .type_attribute("forge.TrafficInterceptBridging", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NetworkPrefix", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NetworkPrefixEvent", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NetworkSegment", "#[derive(serde::Serialize)]")
        .type_attribute("forge.IBPartitionConfig", "#[derive(serde::Serialize)]")
        .type_attribute("forge.IBPartitionStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.IBPartition", "#[derive(serde::Serialize)]")
        .type_attribute("forge.IBPartitionIdList", "#[derive(serde::Serialize)]")
        .type_attribute("forge.IBPartitionList", "#[derive(serde::Serialize)]")
        .type_attribute("forge.PowerOptionResponse",
                        "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("forge.PowerOptions",
                        "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute(
            "forge.InlineIpxe",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("forge.NetworkSegmentList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.OperatingSystem",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.OperatingSystem.variant",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("forge.InterfaceList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.NetworkSegmentStateHistory",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.RackStateHistory",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.Tenant", "#[derive(serde::Serialize)]")
        .type_attribute("forge.TenantContent", "#[derive(serde::Serialize)]")
        .type_attribute("forge.TenantList", "#[derive(serde::Serialize)]")
        .type_attribute("forge.TenantKeyset", "#[derive(serde::Serialize)]")
        .type_attribute("forge.TenantKeysetContent", "#[derive(serde::Serialize)]")
        .type_attribute("forge.TenantKeysetList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.TenantKeysetIdentifier",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.TenantPublicKey", "#[derive(serde::Serialize)]")
        .type_attribute("forge.TenantKeySetList", "#[derive(serde::Serialize)]")
        .type_attribute("forge.VpcResourceState", "#[derive(serde::Serialize)]")
        .type_attribute("forge.MachineBootOverride", "#[derive(serde::Serialize)]")
        .type_attribute("forge.ConnectedDevice", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NetworkDevice", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NetworkTopologyData", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.InstanceInterfaceStatusObservation",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.FabricInterfaceData", "#[derive(serde::Serialize)]")
        .type_attribute("forge.LinkData", "#[derive(serde::Serialize)]")
        .type_attribute("forge.DpuNetworkStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.LastDhcpRequest", "#[derive(serde::Serialize)]")
        .type_attribute("forge.ResourcePool", "#[derive(serde::Serialize)]")
        .type_attribute("forge.DpaInterface", "#[derive(serde::Serialize)]")
        .type_attribute("forge.DpaInterfaceList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.DpaInterfaceStateHistoryRecord",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.Vpc", "#[derive(serde::Serialize)]")
        .type_attribute("forge.VpcStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.VpcList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.StorageClusterAttributes",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.VpcPrefix", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.VpcPrefixConfig",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.VpcPrefixStatus",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.VpcPeering", "#[derive(serde::Serialize)]")
        .type_attribute("forge.VpcPeeringList", "#[derive(serde::Serialize)]")
        .type_attribute("forge.StorageCluster", "#[derive(serde::Serialize)]")
        .type_attribute("forge.StoragePoolAttributes", "#[derive(serde::Serialize)]")
        .type_attribute("forge.StoragePool", "#[derive(serde::Serialize)]")
        .type_attribute("forge.StorageVolumeStatus", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.StorageVolumeAttributes",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.StorageVolume", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.DeleteStoragePoolRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.ListStoragePoolRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.ListStoragePoolResponse",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.DeleteStorageVolumeRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.ListStorageVolumeRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.ListStorageVolumeResponse",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("forge.OsImageAttributes", "#[derive(serde::Serialize)]")
        .type_attribute("forge.OsImage", "#[derive(serde::Serialize)]")
        .type_attribute("forge.ListOsImageRequest", "#[derive(serde::Serialize)]")
        .type_attribute("forge.ListOsImageResponse", "#[derive(serde::Serialize)]")
        .type_attribute("DeleteOsImageRequest", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.MachineDiscoveryInfo",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "common.UUID",
            "#[derive(Ord, PartialOrd, serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.MachineDiscoveryInfo.discovery_data",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.DhcpDiscovery",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.UserRoles",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.BMCRequestType",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "forge.BmcInfo",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "forge.bmc_meta_data_update_request.DataItem",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "DataItem",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "bmc_meta_data_update_request",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "BMCMetaDataUpdateRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "ControllerStateReason",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("ControllerStateSourceReference", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute(
            "RuntimeConfig",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("StateSla", "#[derive(serde::Serialize)]")
        .type_attribute(
            "BuildInfo",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("MachineValidationResultList", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationResult", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationRunList", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationRun", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedHostNic", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedHostNic", "#[derive(serde::Deserialize)]")
        .type_attribute("ExpectedMachine", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedPowerShelf", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedSwitch", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedRack", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedMachineList", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedPowerShelfList", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedSwitchList", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedRackList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "TpmCaCertDetail",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "TpmCaCertDetailCollection",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "TpmEkCertStatus",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "TpmEkCertStatusCollection",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "TpmCaAddedCaStatus",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "TpmCaCertId",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("MachineValidationState", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationCompleted", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationInProgress", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationStarted", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationStatus", "#[derive(serde::Serialize)]")
        .type_attribute(
            "MachineValidationExternalConfig",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "MachineValidationTestUpdateRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "MachineValidationTestAddRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "MachineValidationTest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "MachineValidationTestsGetRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "MachineValidationTestUpdateRequest.Payload",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.RedfishBrowseResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.NetworkSecurityGroup",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "forge.NetworkSecurityGroupStatus",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.NetworkSecurityGroupSource",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "forge.NetworkSecurityGroupRuleDirection",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "forge.NetworkSecurityGroupRuleProtocol",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "forge.NetworkSecurityGroupRuleAction",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.NetworkSecurityGroupAttributes",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "forge.NetworkSecurityGroupRuleAttributes",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .field_attribute(
            "forge.NetworkSecurityGroupRuleAttributes.direction",
            "#[serde(deserialize_with = \"NetworkSecurityGroupRuleDirection::from_string\", serialize_with = \"NetworkSecurityGroupRuleDirection::serialize_from_enum_i32\")]",
        )
        .field_attribute(
            "forge.NetworkSecurityGroupRuleAttributes.protocol",
            "#[serde(deserialize_with = \"NetworkSecurityGroupRuleProtocol::from_string\", serialize_with = \"NetworkSecurityGroupRuleProtocol::serialize_from_enum_i32\")]",
        )
        .field_attribute(
            "forge.NetworkSecurityGroupRuleAttributes.action",
            "#[serde(deserialize_with = \"NetworkSecurityGroupRuleAction::from_string\", serialize_with = \"NetworkSecurityGroupRuleAction::serialize_from_enum_i32\")]",
        )
        .type_attribute(
            "forge.NetworkSecurityGroupRuleAttributes.source_net",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "forge.NetworkSecurityGroupRuleAttributes.source_net",
            "#[serde(rename_all=\"snake_case\")]",
        )
        .type_attribute(
            "forge.NetworkSecurityGroupRuleAttributes.destination_net",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "forge.NetworkSecurityGroupRuleAttributes.destination_net",
            "#[serde(rename_all=\"snake_case\")]",
        )
        .type_attribute(
            "forge.InstanceNetworkRestrictions",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.FlatInterfaceNetworkSecurityGroupConfig",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.ResolvedNetworkSecurityGroupRule",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.NetworkSecurityGroupAttachments",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.NetworkSecurityGroupPropagationObjectStatus",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("Sku", "#[derive(serde::Serialize, serde::Deserialize)]")
        .field_attribute("Sku.schema_version", "#[serde(default)]")
        .field_attribute("Sku.associated_machine_ids", "#[serde(default)]")
        .type_attribute("SkuList", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(
            "SkuComponents",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "SkuComponentChassis",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "SkuComponentCpu",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "common.SwitchId",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "SkuComponentGpu",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "SkuComponentMemory",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "SkuComponentInfinibandDevices",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "SkuComponentEthernetDevices",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "SkuComponentStorage",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .field_attribute("SkuComponentStorage.vendor", "#[serde(default)]")
        .field_attribute("SkuComponentStorage.capacity_mb", "#[serde(default)]")
        .type_attribute(
            "SkuComponentTpm",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute("SkuId", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(
            "SkuStatus",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute("forge.RackFirmware", "#[derive(serde::Serialize)]")
        .type_attribute("forge.RackFirmwareList", "#[derive(serde::Serialize)]")
        .type_attribute("forge.RackFirmwareHistoryRecord", "#[derive(serde::Serialize)]")
        .type_attribute("forge.RackFirmwareHistoryRecords", "#[derive(serde::Serialize)]")
        .type_attribute("forge.RackFirmwareHistoryResponse", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.MachineHardwareInfoGpu",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.ManagedHostQuarantineState",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "forge.ManagedHostQuarantineMode",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("forge.AppliedRemediationIdList", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("forge.AppliedRemediationId", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("forge.AppliedRemediationList", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("forge.AppliedRemediation", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("forge.RemediationList", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("forge.Remediation", "#[derive(serde::Deserialize, serde::Serialize)]")
        .field_attribute("machine_discovery.BlockDevice.device_type", "#[serde(default)]")
        .field_attribute("machine_discovery.NvmeDevice.serial", "#[serde(default)]")
        .type_attribute(
            "forge.InstanceTypeAttributes",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "forge.InstanceType",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "forge.InstanceTypeAllocationStats",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .field_attribute(
            "forge.InstanceTypeMachineCapabilityFilterAttributes.capability_type",
            "#[serde(deserialize_with = \"MachineCapabilityType::from_string\", serialize_with = \"MachineCapabilityType::serialize_from_enum_i32\")]",
        )
        .field_attribute(
            "forge.InstanceTypeMachineCapabilityFilterAttributes.device_type",
            "#[serde(deserialize_with = \"MachineCapabilityDeviceType::from_string\", serialize_with = \"MachineCapabilityDeviceType::serialize_from_enum_i32\")]",
        )
        .type_attribute(
            "forge.InstanceTypeMachineCapabilityFilterAttributes",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "forge.GetRackRequest",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "forge.GetRackResponse",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "forge.DeleteRackRequest",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "forge.Rack",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "forge.RackList",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "common.Uint32List",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute("forge.NVLPartitionConfig", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NVLPartitionStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NVLPartition", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NVLPartitionList", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NVLLogicalPartitionConfig", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NVLLogicalPartitionStatus", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NVLLogicalPartition", "#[derive(serde::Serialize)]")
        .type_attribute("forge.NVLLogicalPartitionList", "#[derive(serde::Serialize)]")

        .type_attribute(
            "common.PowerShelfId",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            ".rack_manager",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            ".nmx_c",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "common.RouteTarget",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "common.MachineId",
            "#[derive(Ord, PartialOrd)]",
        )
        .type_attribute(
            "common.PowerShelfId",
            "#[derive(Ord, PartialOrd)]",
        )
        .type_attribute(
            "common.SwitchId",
            "#[derive(Ord, PartialOrd)]",
        )
        .type_attribute(
            "common.RemediationId",
            "#[derive(serde::Serialize, serde::Deserialize, Ord, PartialOrd)]",
        )
        .type_attribute("common.StringList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "forge.InstanceAllocationRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.RouteServerEntries",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.RouteServer",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.ComputeAllocation",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.ComputeAllocationAttributes",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "forge.GetBmcCredentialsRequest",
            "#[derive(serde::Serialize)]",
        )
        .build_server(true)
        .build_client(true)
        .protoc_arg("--experimental_allow_proto3_optional")
        .out_dir(autogenerated_rust_output_directory)
        .compile_protos(
            &[
                "proto/common.proto",
                "proto/forge.proto",
                "proto/dpa_rpc.proto",
                "proto/machine_discovery.proto",
                "proto/mlx_device.proto",
                "proto/nmx_c.proto",
                "proto/site_explorer.proto",
                "proto/dns.proto",
                "proto/fmds.proto",
            ],
            &["proto"],
        )
        .unwrap();

    let client_wrapper_generator = codegen::CodeGenerator::new(codegen::Config {
        wrapper_name: "ForgeApiClient".to_string(),
        inner_rpc_client_type: "crate::forge_tls_client::ForgeClientT".to_string(),
        proto_files: vec!["proto/forge.proto".to_string()],
        include_paths: vec!["proto".to_string()],
        generated_types_path_within_crate: "protos".to_string(),
        extern_paths: vec![
            (".common.MachineId", "::carbide_uuid::machine::MachineId"),
            (".common.DomainId", "::carbide_uuid::domain::DomainId"),
            (
                ".common.RemediationId",
                "::carbide_uuid::dpu_remediations::RemediationId",
            ),
            (
                ".common.MachineInterfaceId",
                "::carbide_uuid::machine::MachineInterfaceId",
            ),
            (".common.VpcId", "::carbide_uuid::vpc::VpcId"),
            (".common.VpcPrefixId", "::carbide_uuid::vpc::VpcPrefixId"),
            (
                ".common.VpcPeeringId",
                "::carbide_uuid::vpc_peering::VpcPeeringId",
            ),
            (
                ".common.IBPartitionId",
                "::carbide_uuid::infiniband::IBPartitionId",
            ),
            (".common.InstanceId", "::carbide_uuid::instance::InstanceId"),
            (
                ".common.NetworkSegmentId",
                "::carbide_uuid::network::NetworkSegmentId",
            ),
            (
                ".common.DpaInterfaceId",
                "::carbide_uuid::dpa_interface::DpaInterfaceId",
            ),
            (
                ".common.NetworkPrefixId",
                "::carbide_uuid::network::NetworkPrefixId",
            ),
            (".common.SwitchId", "::carbide_uuid::switch::SwitchId"),
            (
                ".common.PowerShelfId",
                "::carbide_uuid::power_shelf::PowerShelfId",
            ),
            (
                ".common.ComputeAllocationId",
                "::carbide_uuid::compute_allocation::ComputeAllocationId",
            ),
            (".common.RackId", "::carbide_uuid::rack::RackId"),
            (
                ".common.NVLinkPartitionId",
                "::carbide_uuid::nvlink::NvLinkPartitionId",
            ),
            (
                ".common.NVLinkLogicalPartitionId",
                "::carbide_uuid::nvlink::NvLinkLogicalPartitionId",
            ),
            (
                ".common.NVLinkDomainId",
                "::carbide_uuid::nvlink::NvLinkDomainId",
            ),
            (
                ".measured_boot.MeasurementSystemProfileId",
                "::carbide_uuid::measured_boot::MeasurementSystemProfileId",
            ),
            (
                ".measured_boot.MeasurementSystemProfileAttrId",
                "::carbide_uuid::measured_boot::MeasurementSystemProfileAttrId",
            ),
            (
                ".measured_boot.MeasurementBundleId",
                "::carbide_uuid::measured_boot::MeasurementBundleId",
            ),
            (
                ".measured_boot.MeasurementBundleValueId",
                "::carbide_uuid::measured_boot::MeasurementBundleValueId",
            ),
            (
                ".measured_boot.MeasurementReportId",
                "::carbide_uuid::measured_boot::MeasurementReportId",
            ),
            (
                ".measured_boot.MeasurementReportValueId",
                "::carbide_uuid::measured_boot::MeasurementReportValueId",
            ),
            (
                ".measured_boot.MeasurementJournalId",
                "::carbide_uuid::measured_boot::MeasurementJournalId",
            ),
            (
                ".measured_boot.MeasurementApprovedMachineId",
                "::carbide_uuid::measured_boot::MeasurementApprovedMachineId",
            ),
            (
                ".measured_boot.MeasurementApprovedProfileId",
                "::carbide_uuid::measured_boot::MeasurementApprovedProfileId",
            ),
        ],
    })?;

    client_wrapper_generator.write_rpc_client_wrapper("src/protos/forge_api_client.rs")?;
    client_wrapper_generator
        .write_rpc_convenience_converters("src/protos/convenience_converters.rs")?;

    // enable the code generator for the nmx-c proto
    let nmx_c_client_wrapper = codegen::CodeGenerator::new(codegen::Config {
        wrapper_name: "NmxCApiClient".to_string(),
        inner_rpc_client_type: "crate::forge_tls_client::NmxCClientT".to_string(),
        proto_files: vec!["proto/nmx_c.proto".to_string()],
        include_paths: vec!["proto".to_string()],
        extern_paths: vec![],
        generated_types_path_within_crate: "protos".to_string(),
    })?;
    nmx_c_client_wrapper.write_rpc_client_wrapper("src/protos/nmx_c_client.rs")?;
    nmx_c_client_wrapper.write_rpc_convenience_converters("src/protos/nmx_c_converters.rs")?;

    Ok(())
}
