#!/bin/sh
set -e

. /usr/share/debconf/confmodule

if [ "$1" = "configure" ]; then
	# Ensure the core file directory exists
	# Must match /proc/sys/kernel/core_pattern
	mkdir -p /var/support/core

	systemctl daemon-reload
	systemctl enable local_bmc_dev.service
	systemctl enable forge-dpu-agent.service
	systemctl enable otelcol-contrib.service
	systemctl enable node-exporter.service
	systemctl enable transceiver-exporter.service

	if [ -f /etc/otelcol-contrib/fd_configs/fd_discovery.yaml ]; then
		rm -f /etc/otelcol-contrib/fd_configs/fd_discovery.yaml
	fi
	if [ -d /etc/otelcol-contrib/fd_configs ]; then
		rmdir --ignore-fail-on-non-empty /etc/otelcol-contrib/fd_configs
	fi
	# Do not depend on starting services now, as this package is installed early in setup
	# and should not hang or cause out of order steps in discovery workflows. The discovery
	# workflow will reboot shortly after this package is installed, so it is best to rely
	# on the reboot process to start the services enabled above.

	if [ -n "$2" ]; then
 		# The package is being upgraded and not installed for the first time, so
 		# this is not the discovery workflow and otelcol-contrib can restart without
 		# interfering. Restart is needed to pick up any configuration changes.

		systemctl restart transceiver-exporter.service
		systemctl restart node-exporter.service
		systemctl restart otelcol-contrib.service
	fi
fi
