#
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This should match rust-toolchain.toml
ARG CONTAINER_BUILD_X86_64
ARG CONTAINER_RUNTIME_X86_64

FROM $CONTAINER_BUILD_X86_64 as builder
ARG CI_COMMIT_SHORT_SHA
ENV CI_COMMIT_SHORT_SHA $CI_COMMIT_SHORT_SHA

ARG VERSION
ENV VERSION $VERSION
ENV CONTAINER_REPO_ROOT=/carbide

RUN USER=root cargo new --bin carbide
WORKDIR ./carbide
COPY . ./

RUN export CARGO_MAKE_SKIP_CODECOV="true" && \
  export DATABASE_URL="postgresql://%2Fvar%2Frun%2Fpostgresql" && \
  export SCCACHE_DIR=/sccache && \
  export RUST_WRAPPER=sccache && \
  /etc/init.d/postgresql start && \
  sudo -u postgres psql -c "ALTER USER root WITH SUPERUSER;" && \
  createdb root && \
  cargo make build-and-test-release-container-services && \
  echo "$(date): Finished cargo make build-and-test-release-container-services\n" && \
  mkdir -p /carbide/target/bin && \
  find /carbide/target/release -maxdepth 1 -type f -exec cp -t /carbide/target/bin {} + && \
  rm -rf /carbide/target/debug && \
  rm -rf /carbide/target/release && \
  echo "$(date): Deleted artifacts"

# After build, copy the release into the runtime container
FROM $CONTAINER_RUNTIME_X86_64
RUN mkdir -p /opt/carbide/migrations && \
  mkdir -p /opt/carbide/pxe/templates && \
  mkdir -p /opt/carbide/static

RUN echo "$(date): Start runtime container build"

COPY --from=builder ["/carbide/target/bin/carbide-api", "/carbide/target/bin/carbide", "/carbide/target/bin/carbide-dns", "/carbide/target/bin/carbide-admin-cli", "/carbide/target/bin/carbide-dsx-exchange-consumer", "/carbide/target/bin/forge-dpu-agent", "/carbide/target/bin/forge-dhcp-server", "/carbide/target/bin/forge-hw-health", "/carbide/target/bin/forge-log-parser", "/carbide/target/bin/ssh-console", "/opt/carbide/"]
COPY --from=builder /carbide/target/bin/libdhcp.so /usr/lib/x86_64-linux-gnu/kea/hooks
RUN ln -s /opt/carbide/carbide-admin-cli /opt/carbide/forge-admin-cli

RUN echo "$(date): Finished copies"

COPY crates/api-db/migrations/ /opt/carbide/migrations/
COPY pxe/templates/*  /opt/carbide/pxe/templates/
COPY crates/api/casbin-policy.csv /opt/carbide/

ENV CASBIN_POLICY_FILE=/opt/carbide/casbin-policy.csv
